services:
  - type: web
    name: tiptop-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://tiptop-event-1.onrender.com

  - type: static
    name: tiptop-frontend
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    envVars:
      - key: VITE_API_URL
        value: https://tiptop-events.onrender.com/api
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache, no-store, must-revalidate