services:
  - type: web
    name: tiptop-frontend
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm run preview
    staticPublishPath: ./client/docs
    envVars:
      - key: VITE_API_URL
        value: https://tiptop-event-1.onrender.com/api

  - type: web
    name: tiptop-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://tiptop-event-1.onrender.com